[package]
name = "scanscan-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
scanscan-ipc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rayon = "1"
memmap2 = "0.9"
globset = "0.4"
zstd = "0.13"
blake3 = "1"

[dev-dependencies]
tempfile = "3"
